---
- hosts: manager
  become: true
  vars_files:
    - "../vars/vars.yml"
    - "../vars/vault.yml"
  vars:
    image_registry: "ghcr.io"
    challenge_image: ""
    challenge_port: 3000

  tasks:
    - name: log in to container registry
      community.docker.docker_login:
        registry_url: "{{ image_registry }}"
        username: "{{ image_registry_username }}"
        password: "{{ image_registry_password }}"

    - name: create challenge network
      community.docker.docker_network:
        state: present
        name: challenge_network
        driver: overlay
        driver_options:
          ingress: true
        scope: global

    - name: create postgres volume
      community.docker.docker_volume:
        name: postgres_volume

    - name: create postgres service
      community.docker.docker_swarm_service:
        name: "{{ postgres_hostname }}"
        image: "postgres:17"
        networks:
          - challenge_network
        mounts:
          - source: postgres_volume
            target: "/var/lib/postgresql/data"
            type: volume
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "{{ postgres_db }}"
          POSTGRES_USER: "{{ postgres_user }}"

    - name: create challenge service
      community.docker.docker_swarm_service:
        name: challenge
        image: "{{ challenge_image }}"
        networks:
          - challenge_network
        env:
          DATABASE_URL: "{{ postgres_url }}"
        publish:
          - published_port: 80
            target_port: "{{ challenge_port | int }}"
