---
- name: "Docker"
  hosts: all
  become: true
  tasks:
    - name: Wait for sudo
      become: true
      changed_when: false
      ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: Wait for sudo
      become: true
      changed_when: false
      ansible.builtin.shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
