name: deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TERRAFORM_DIR: terraform

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Set version
        id: release
        run: echo ::set-output name=version::$(git describe --always)

      - name: Set image details
        id: image
        env:
          IMAGE_TAG: ${{ steps.release.outputs.version }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          IMAGE_NAME_LC="${IMAGE_NAME,,}"
          echo "IMAGE_NAME_LC=$IMAGE_NAME_LC" >> ${GITHUB_ENV}
          echo "IMAGE_NAME_FULL_LC=${{ env.REGISTRY }}/$IMAGE_NAME_LC:${{ env.IMAGE_TAG }}" >> ${GITHUB_ENV}

      - name: Build container image
        run: DATABASE_URL=postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/pilots docker build  -t "${{ env.IMAGE_NAME_FULL_LC }}" challenge
      
      - name: Docker Login
        run: echo ${{ secrets.CI_PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: Push image to Docker Registry
        env:
          IMAGE_TAG: ${{ steps.release.outputs.version }}
        run: docker push "${{ env.IMAGE_NAME_FULL_LC }}"
      
      - name: Deploy
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_image_registry: ${{ env.REGISTRY }}
          TF_VAR_challenge_image_name: ${{ env.IMAGE_NAME_LC }}
          TF_VAR_challenge_image_tag: ${{ steps.release.outputs.version }}
        run: |
          # install opentofu
          scripts/install-opentofu.sh --install-method deb
          tofu -version
          # apply infra changes
          tofu -chdir=$TERRAFORM_DIR init
          tofu -chdir=$TERRAFORM_DIR validate
          tofu -chdir=$TERRAFORM_DIR plan -out .terraform-plan
          tofu -chdir=$TERRAFORM_DIR apply .terraform-plan